/* ข้อมูลทริป — แก้ข้อความ/เวลาได้ที่ไฟล์นี้ไฟล์เดียว */
const CHECKED = '5 ต.ค. 2026';
const BUILD = '5 ต.ค. 2026 (ฉบับ 3)';

const enc = encodeURIComponent;
const gdir = (o, d, mode) => `https://www.google.com/maps/dir/?api=1&origin=${enc(o)}&destination=${enc(d)}&travelmode=${mode || 'transit'}`;
const gsearch = q => `https://www.google.com/maps/search/?api=1&query=${enc(q)}`;

const HOTEL = 'Hotel 81 Dickson, 3 Dickson Rd, Singapore 209530';
const MAP_IMG = 'https://storage.singaporegp.sg/web/2026/circuit-park-map/circuit-park-map-08.jpg';

const SRC = {
  f1tt: { label: 'Formula1.com – ตารางเวลาเต็ม Singapore GP 2026', url: 'https://www.formula1.com/en/latest/article/formula-1-singapore-airlines-singapore-grand-prix-2026.1OXwlTH5jrpTiZX2Dvg7qE' },
  ent: { label: 'singaporegp.sg – ตารางเวที 2026', url: 'https://singaporegp.sg/en/entertainment/' },
  fanforum: { label: 'singaporegp.sg – F1 Drivers’ Fan Forum 2026', url: 'https://singaporegp.sg/en/entertainment/2026-fan-forum-f1-drivers/' },
  hours: { label: 'singaporegp.sg – เวลาเปิด-ปิดสนาม 2026', url: 'https://singaporegp.sg/en/event-info/eventguide/general/circuit-park-opening-hours/' },
  flyer: { label: 'singaporegp.sg – Complimentary Singapore Flyer Rides 2026', url: 'https://singaporegp.sg/en/event-info/eventguide/event-tips/singapore-flyer-rides/' },
  flyerSite: { label: 'singaporeflyer.com – Formula 1 Updates', url: 'https://www.singaporeflyer.com/en/formula-1-updates' },
  pwGuide: { label: 'singaporegp.sg – วิธีเข้าสนามสำหรับ Premier Walkabout (ณ 15 ก.ย. 2026)', url: 'https://singaporegp.sg/en/event-info/eventguide/getting-here/gt-general/premier-walkabout/' },
  pwTicket: { label: 'singaporegp.sg – บัตร Premier Walkabout 2026', url: 'https://singaporegp.sg/en/tickets/general-tickets/walkabouts/premier-walkabout/' },
  z4Guide: { label: 'singaporegp.sg – วิธีเข้า Zone 4 (Gate 3A/3B/4/5/6/7)', url: 'https://singaporegp.sg/en/event-info/eventguide/getting-here/gt-general/zone-4-walkabout/' },
  out3: { label: 'singaporegp.sg – ออกจาก Gate 3A/3B', url: 'https://singaporegp.sg/en/event-info/eventguide/getting-here/getting-out/gate-3-a-3-b-stamford/' },
  out1: { label: 'singaporegp.sg – ออกจาก Gate 1', url: 'https://singaporegp.sg/en/event-info/eventguide/getting-here/getting-out/gate-1-a-republic-boulevard-and-gate-1-b-nicoll-highway/' },
  padang: { label: 'singaporegp.sg – Journey to the Padang Stage', url: 'https://singaporegp.sg/en/event-info/eventguide/event-tips/quicken-your-journey-to-the-padang-stage/' },
  trackwalk: { label: 'singaporegp.sg – Track Walk', url: 'https://singaporegp.sg/en/event-info/eventguide/event-tips/track-walk/' },
  fanzone: { label: 'singaporegp.sg – Concert Fan Zone at Padang Stage', url: 'https://singaporegp.sg/en/event-info/eventguide/event-tips/concert-fan-zone-at-padang-stage/' },
  prohibited: { label: 'singaporegp.sg – Advisories & Prohibited Items 2026', url: 'https://singaporegp.sg/en/event-info/eventguide/general/prohibited-items/' },
  gear: { label: 'singaporegp.sg – Gear Up, Rain or Shine', url: 'https://singaporegp.sg/en/event-info/eventguide/event-tips/gear-up-rain-or-shine/' },
  ticketing: { label: 'singaporegp.sg – Ticketing Info (บัตรในแอป)', url: 'https://singaporegp.sg/en/event-info/eventguide/general/ticketing-info/' },
  map: { label: 'แผนที่สนามทางการ 2026 (ข้อมูล ณ 10 ก.ย. 2026)', url: MAP_IMG },
  lta: { label: 'LTA OneMotoring – F1 2026 (สถานี/ทางออกต่อ Gate, รถเที่ยวสุดท้าย)', url: 'https://onemotoring.lta.gov.sg/content/onemotoring/home/driving/formula-1-singapore-airlines-singapore-grand-prix-2026.html' },
  ltaNews: { label: 'LTA – ข่าว 4 ก.ย. 2026 ขยายเวลารถไฟ/รถเมล์ช่วง F1', url: 'https://www.lta.gov.sg/content/ltagov/en/newsroom/2026/9/news-releases/road-closure-and-transport-arrangements-f1-spore-grand-prix-26.html' },
  ltaPay: { label: 'LTA – วิธีจ่ายค่ารถไฟ/รถเมล์ (F1 2026)', url: 'https://onemotoring.lta.gov.sg/content/dam/onemotoring/Driving/f1/2026/pdf/F1%202026%20Payment%20Modes%20for%20Train%20and%20Bus%20Rides.pdf' },
  fare: { label: 'LTA – Fare Calculator', url: 'https://www.lta.gov.sg/content/ltagov/en/map/fare-calculator.html' },
  lemon: { label: 'Lemon8 @starklypositive – วิดีโอโค้ง 7 จากบัตร Zone 4 Walkabout (โพสต์ 22 ก.ย. 2024)', url: 'https://www.lemon8-app.com/@starklypositive/7417320491767087633?region=sg' },
  offPW: { label: 'singaporegp.sg – ภาพประกอบหน้าบัตร Premier Walkabout 2026', url: 'https://singaporegp.sg/en/tickets/general-tickets/walkabouts/premier-walkabout/' },
  offZ4: { label: 'singaporegp.sg – ภาพประกอบหน้าบัตร Zone 4 Walkabout 2026', url: 'https://singaporegp.sg/en/tickets/general-tickets/walkabouts/zone-4-walkabout/' },
  fly: { label: 'Fly F1 Travel (ภาพปี 2025)', url: 'https://flyf1travel.com/' },
  note: { label: 'note.com/torazou_il – บันทึกผู้ชมปี 2025 (บัตร Zone 4 Walkabout)', url: 'https://note.com/torazou_il/n/ndfe39a1d6789' },
  reddit1: { label: 'Reddit r/GrandPrixTravel – ประสบการณ์ Walkabout ปี 2025', url: 'https://www.reddit.com/r/GrandPrixTravel/comments/1nyriwp/avoid_walkabout_tickets_as_of_2025_singapore/' },
  reddit2: { label: 'Reddit r/GrandPrixTravel – First F1 race Singapore ’25', url: 'https://www.reddit.com/r/GrandPrixTravel/comments/1icnhdz/first_f1_race_singapore_25/' },
  shaun: { label: 'shaunchng.com – เดินสำรวจ Singapore GP 2025', url: 'https://shaunchng.com/running-sports/sports-events/formula-1-singapore-gp-2025-explorations/' },
  hotel: { label: 'ข้อมูลโรงแรมจากเว็บจองห้อง (ระยะถึงสถานี)', url: 'https://www.agoda.com/hotel-81-dickson/hotel/singapore-sg.html' },
  rate: { label: 'ValutaFX – THB→SGD', url: 'https://www.valutafx.com/convert/thb-sgd' },
  sgac: { label: 'ICA – SG Arrival Card', url: 'https://eservices.ica.gov.sg/sgarrivalcard/' },
  ahtai: { label: 'Miss Tam Chiak – Ah Tai (เวลาเปิดจากรีวิว)', url: 'https://www.misstamchiak.com/ah-tai-hainanese-chicken-rice/' },
  btrt: { label: 'Buddha Tooth Relic Temple – เว็บวัด', url: 'https://www.buddhatoothrelictemple.org.sg/' },
  kwanim: { label: 'Time Out – Kwan Im Thong Hood Cho Temple', url: 'https://timeout.com/singapore/things-to-do/kwan-im-thong-hood-cho-temple' },
  tbb: { label: 'Time Out – Tiong Bahru Bakery Foothills (Fort Canning)', url: 'https://www.timeout.com/singapore/restaurants/tiong-bahru-bakery-foothills' },
  ngkuan: { label: 'Eatbook – ร้าน Chilli Pan Mee ในสิงคโปร์', url: 'https://eatbook.sg/chilli-pan-mee-singapore/' },
};

/* สถานะข้อมูล: ok=ยืนยันทางการ 2026, tip=คำแนะนำ, prev=ประสบการณ์ปีก่อน, unk=ยังไม่ยืนยัน */

const RETURN_HOTEL = {
  id: 'ret', t: 'rt', title: 'กลับ Hotel 81 Dickson หลังจบงาน',
  from: 'Zone 4 (Padang / Memorial)', to: 'Hotel 81 Dickson',
  total: '35–70 นาที', walk: 'ราว 15–25 นาที', ride: '2–3 นาที (1 สถานี)', buffer: 'คิวออกประตู + รอเข้าสถานี 15–40 นาที',
  leave: null,
  leaveWhy: 'สนามปิด 00:00 ทุกคืน · รถไฟสาย North-South / East-West เที่ยวสุดท้ายออกจาก City Hall เวลา 00:30 (คืนศุกร์-เสาร์) และ 00:45 (คืนอาทิตย์)',
  steps: [
    'ออกทาง <b>Gate 3A / 3B (Stamford)</b> — ประตูที่ใกล้ Padang และ Memorial ที่สุด',
    'เดินไป <b>City Hall MRT ทางออก A</b> (ทางการบอกเดิน 5–10 นาทีในขาเข้า ขาออกคนแน่นจะนานกว่า)',
    'ขึ้นสาย East-West (สีเขียว) ฝั่งไป Pasir Ris <b>1 สถานี ลง Bugis</b>',
    'เดินจาก Bugis กลับโรงแรม ราว 600–700 ม. (ประมาณจากพิกัด ไม่ใช่วัดจริง)',
  ],
  alt: [
    '<b>เดินกลับทั้งเส้น</b> — Gate 3B ถึงโรงแรมราว 1.5–1.8 กม. เดิน 20–30 นาที (ประมาณจากพิกัด) ถ้าคิวเข้าสถานียาว วิธีนี้อาจถึงก่อน',
    '<b>Esplanade MRT ทางออก F</b> (Circle Line) → Promenade → เปลี่ยน Downtown Line → Rochor ใกล้โรงแรมกว่า แต่ <b>ยังไม่พบเวลารถเที่ยวสุดท้ายของ Downtown Line ปี 2026</b> อย่าใช้เส้นนี้หลังเที่ยงคืนถ้ายังไม่ได้ถามเจ้าหน้าที่',
    '<b>แท็กซี่</b> — จุดขึ้นหน้า Capitol Singapore (North Bridge Rd) และ Coleman St · มีค่าเพิ่ม S$8 ช่วง 21:30–00:00 · Grab รับที่ Raffles City (ฝั่ง North Bridge Rd), South Beach Tower (Middle Rd) หรือ Funan',
  ],
  warn: 'ประกาศ LTA ที่อ่านได้ไม่แยกทิศทางของรถเที่ยวสุดท้าย และบอกให้ถามเวลาที่ Passenger Service Centre ในสถานี — ถามตอนขาเข้าไว้เลย ถ้าพลาดรถ ใช้วิธีเดินกลับหรือแท็กซี่',
  status: 'ok', src: [SRC.out3, SRC.lta, SRC.ltaNews, SRC.hours],
  maps: gdir('City Hall MRT Station, Singapore', HOTEL), mapsLabel: 'เปิด Google Maps: City Hall → โรงแรม', pin: 'g3a',
};

const DAYS = [
  {
    id: 'd1', date: '2026-10-09', tab: 'Day 1', label: 'ศุกร์ 9 ต.ค.', title: 'บินเข้า · CORTIS · Sprint Qualifying',
    items: [
      { id: 'd1-fly', t: 'ev', s: '12:15', e: '14:30', icon: '✈️', title: 'เที่ยวบินไปสิงคโปร์', place: 'BKK → Changi T2',
        plan: '11:15 (เวลาไทย) – 14:30 (เวลาสิงคโปร์)', status: 'tip',
        detail: 'เวลาออก 11:15 เป็นเวลาไทย · เวลาถึง 14:30 เป็นเวลาสิงคโปร์ (เร็วกว่าไทย 1 ชม.) ช่วงนี้คือเวลาบิน ไม่ใช่เวลาที่ต้องอยู่สนามบิน<br>ก่อนบิน: กรอก <b>SG Arrival Card</b> ออนไลน์ล่วงหน้า (ทำได้ภายใน 3 วันก่อนถึง) และโหลดบัตร F1 ลงแอป Singapore GP ให้เรียบร้อย',
        src: [SRC.sgac, SRC.ticketing] },
      { id: 'd1-imm', t: 'ev', s: '15:00', e: '16:30', icon: '🛂', title: 'รับกระเป๋า + Immigration', place: 'Changi Airport Terminal 2', plan: '15:00–16:30', status: 'tip',
        detail: 'เข้าห้องน้ำ เติมน้ำ และเตรียมบัตรที่จะใช้แตะ MRT ก่อนลงไปสถานี' },
      { id: 'd1-r1', t: 'rt', mm: [45, 60], title: 'Changi T2 → Hotel 81 Dickson', from: 'Changi Airport T2', to: 'Hotel 81 Dickson',
        leave: '16:45', leaveWhy: 'ตามแพลนเดิม 16:45–17:45 · เวลาเดินทางจริงประมาณ 45–60 นาที พอดีกับช่วงที่วางไว้',
        total: '45–60 นาที', walk: '8–12 นาที (ในสนามบิน + สถานีถึงโรงแรม)', ride: 'ราว 35–40 นาที', buffer: 'รอรถ/เปลี่ยนขบวน 5–10 นาที',
        steps: [
          'เดินตามป้าย <b>Train to City</b> ใน T2 ลงสถานี <b>Changi Airport (CG2)</b>',
          'นั่ง 1 สถานีไป <b>Expo (CG1/DT35)</b>',
          'เปลี่ยนเป็น <b>Downtown Line (สีน้ำเงิน)</b> ฝั่งไป Bukit Panjang',
          'ลง <b>Jalan Besar (DT22)</b> — นั่งยาวไม่ต้องเปลี่ยนอีก',
          'เดินไปโรงแรม ราว 120 ม. (ตัวเลขจากเว็บจองห้อง)',
        ],
        alt: ['ถ้ากระเป๋าหนักหรือเหนื่อย: แท็กซี่/Grab จาก T2 ตรงถึงโรงแรม (ถนนแถวโรงแรมอยู่นอกเขตปิดถนน F1)'],
        warn: 'ยังไม่ได้ยืนยันตัวอักษรทางออกของสถานี Jalan Besar — ดูป้าย Dickson Rd ในสถานี',
        status: 'tip', src: [SRC.hotel, SRC.ltaPay], maps: gdir('Changi Airport Terminal 2, Singapore', HOTEL) },
      { id: 'd1-ci', t: 'ev', s: '18:00', e: '18:30', icon: '🏨', title: 'Check-in', place: 'Hotel 81 Dickson', plan: '18:00–18:30', status: 'tip',
        detail: 'เตรียมของเข้าสนาม: บัตรในแอป · ขวดน้ำไม่เกิน 1 ลิตร · ที่อุดหู · เสื้อกันฝน · กระเป๋าไม่เกิน 20 ลิตร', maps: gsearch(HOTEL) },
      { id: 'd1-mc', t: 'ev', s: '18:30', e: '19:00', icon: '🍔', title: 'McDonald’s', place: 'ยังไม่ระบุสาขา', plan: '18:30–19:00', status: 'unk',
        detail: 'แพลนเดิมไม่ได้ระบุสาขา ปุ่มด้านล่างจะค้นสาขาใกล้โรงแรมให้ · ห้ามนำอาหาร/เครื่องดื่มจากข้างนอกเข้าสนาม กินให้เสร็จก่อน',
        src: [SRC.prohibited], maps: gsearch("McDonald's near Hotel 81 Dickson Singapore"), mapsLabel: 'ค้นหา McDonald’s ใกล้โรงแรม' },
      { id: 'd1-r2', t: 'rt', mm: [30, 45], title: 'โรงแรม → Gate 3A/3B → Padang Stage', from: 'Hotel 81 Dickson', to: 'Zone 4 Padang Stage',
        leave: '19:00', leaveWhy: 'แพลนเดิมออก 19:00 ถึง 19:30 ซึ่งตรงกับเวลา CORTIS เริ่มพอดี เส้นทางนี้ใช้ 30–45 นาทีเมื่อรวมคิวตรวจกระเป๋า <b>มีโอกาสพลาดต้นโชว์ 5–15 นาที</b> ถ้าอยากทันเพลงแรก ต้องออกราว 18:45',
        total: '30–45 นาที', walk: '15–20 นาที', ride: '5–8 นาที', buffer: 'รอรถ 3–5 นาที + คิวตรวจกระเป๋า/สแกนบัตร 5–15 นาที',
        steps: [
          'เดินไป <b>Rochor (DT13)</b> ราว 270 ม. (ตัวเลขจากเว็บจองห้อง)',
          'Downtown Line ฝั่งไป Expo <b>2 สถานี ลง Promenade (DT15)</b>',
          'เปลี่ยน <b>Circle Line</b> ฝั่งไป Dhoby Ghaut <b>1 สถานี ลง Esplanade (CC3)</b>',
          'ออก <b>ทางออก F</b> เดินไป <b>Gate 3A / 3B (Stamford)</b>',
          'ผ่านจุดตรวจแล้ว ลอด <b>ทางลอด A หรือ B</b> (ใกล้โค้ง 8) ข้ามไปฝั่ง Padang',
        ],
        alt: [
          'เดินไป Bugis (สายสีเขียว) ราว 600–700 ม. → 1 สถานี ลง <b>City Hall ทางออก A</b> → เดิน 5–10 นาทีถึง Gate 3A/3B (เวลาเดินนี้เป็นตัวเลขทางการ)',
          'เดินทั้งเส้นจากโรงแรมถึง Gate 3B ราว 1.5–1.8 กม. 20–30 นาที (ประมาณจากพิกัด)',
        ],
        warn: 'ทางการให้ Esplanade ทางออก F เป็นสถานีของ Gate 3A/3B แต่ไม่ได้บอกเวลาเดิน · Gate ฝั่ง Zone 4 เปิด 14:00 วันศุกร์',
        status: 'ok', src: [SRC.out3, SRC.z4Guide, SRC.lta, SRC.hours, SRC.map], maps: gdir(HOTEL, 'Esplanade MRT Station Exit F, Singapore'), pin: 'g3a' },
      { id: 'd1-cortis', t: 'ev', s: '19:30', e: '20:20', icon: '🎤', title: 'CORTIS', place: 'Zone 4 · Padang Stage', plan: '19:30–20:20',
        official: { time: '19:30–20:20', note: 'ตรงกับแพลน' }, status: 'ok', src: [SRC.ent], pin: 'padang',
        detail: 'โซนหน้าเวที (Fan Zone) เข้าตามลำดับมาก่อนได้ก่อน ออกแล้วอาจกลับเข้าไม่ได้ถ้าเต็ม · ถ้าจะไปดู Sprint Qualifying ต่อ ยืนฝั่งที่ออกไปทางลอด A/B ได้ง่าย' },
      { id: 'd1-r3', t: 'rt', mm: [8, 15], title: 'Padang → จุดดูรถ Memorial (โค้ง 7–8)', from: 'Padang Stage', to: 'แท่น Walkabout ฝั่ง Stamford / Memorial',
        leave: '20:15', leaveWhy: 'CORTIS จบ 20:20 และ Sprint Qualifying เริ่ม 20:30 มีเวลา 10 นาที ต้องลอดทางลอดพร้อมคนทั้ง Padang ถ้าออก 20:15 จะ<b>พลาดท้ายโชว์ราว 5 นาที</b> ถ้าอยู่จนจบอาจ<b>พลาดช่วงต้น SQ1 ราว 5–10 นาที</b>',
        total: '8–15 นาที', walk: '8–15 นาที (ขึ้นกับคนในทางลอด)', ride: '—', buffer: 'หาที่ยืนบนแท่น',
        steps: ['จาก Padang เดินไปทาง Connaught Drive / โค้ง 8', 'ลอด <b>ทางลอด A หรือ B</b> กลับไปฝั่ง Stamford', 'แท่น Walkabout อยู่รอบ Civilian War Memorial ริมช่วงโค้ง 7 → 8'],
        alt: ['ถ้าแท่นฝั่ง Memorial เต็ม: แท่นริม Raffles Avenue ใกล้ Gate 7 (โค้ง 14–15) — บันทึกผู้ชมปี 2025 บอกว่าคนน้อยกว่า'],
        warn: 'ทางเดินนี้อ่านจากแผนที่ทางการ ยังไม่มีเวลาเดินที่ทางการระบุ',
        status: 'tip', src: [SRC.map, SRC.note], pin: 't7', spot: 't7' },
      { id: 'd1-sq', t: 'ev', s: '20:30', e: '21:14', icon: '🏎️', title: 'F1 Sprint Qualifying', place: 'จุดดูตั้งต้น: Memorial / โค้ง 7–8 (Zone 4)', plan: '20:30–21:14',
        official: { time: '20:30–21:14', note: 'ตรงกับแพลน' }, status: 'ok', src: [SRC.f1tt], spot: 't7', pin: 't7',
        detail: 'รอบคัดเลือกสั้น 3 ช่วง รถวิ่งทีละคันผ่านหน้าเร็ว ใส่ที่อุดหู' },
      { id: 'd1-back', t: 'ev', icon: '🛏️', title: 'กลับ Hotel 81 Dickson และพัก', place: 'ไม่ไป DJ Snake', plan: 'หลังจบ Sprint Qualifying', status: 'tip', ret: true,
        detail: 'ออก Gate 3A/3B ซึ่งอยู่ฝั่งเดียวกับจุดดู Memorial ไม่ต้องลอดทางลอดอีก · คืนนี้ยังมีโชว์อื่นต่อ คนออกพร้อมกันไม่มาก น่าจะออกง่ายกว่าคืนเสาร์-อาทิตย์' },
    ],
  },
  {
    id: 'd2', date: '2026-10-10', tab: 'Day 2', label: 'เสาร์ 10 ต.ค.', title: 'Chinatown · Flyer · Sprint · Qualifying · The Killers',
    items: [
      { id: 'd2-wake', t: 'ev', s: '09:00', e: '10:30', icon: '⏰', title: 'ตื่นและแต่งตัว', place: 'Hotel 81 Dickson', plan: '09:00–10:30', status: 'tip',
        detail: 'วันนี้ยาวถึงเกือบเที่ยงคืน ใส่รองเท้าที่ยืนนานได้ · เข้าวัดช่วงเช้า: เลี่ยงเสื้อแขนกุด/กางเกงขาสั้นมาก หรือพกผ้าคลุมไป' },
      { id: 'd2-r1', t: 'rt', mm: [20, 30], title: 'โรงแรม → Chinatown', from: 'Hotel 81 Dickson', to: 'Maxwell Food Centre / Buddha Tooth Relic Temple',
        leave: '10:30', leaveWhy: 'ตามแพลนเดิม 10:30–11:00 · Ah Tai เปิด 11:00 (ข้อมูลจากรีวิว)',
        total: '20–30 นาที', walk: '8–12 นาที', ride: 'ราว 6–8 นาที (3 สถานี)', buffer: 'รอรถ 3–5 นาที',
        steps: ['เดินไป <b>Jalan Besar (DT22)</b> ราว 120 ม.', 'Downtown Line ฝั่งไป Expo <b>3 สถานี ลง Chinatown (DT19)</b> ไม่ต้องเปลี่ยนสาย', 'เดินไป Maxwell Food Centre / วัดพระเขี้ยวแก้ว (อยู่ติดกัน)'],
        alt: ['สถานี Maxwell (สายสีน้ำตาล TE) อยู่ติด Maxwell Food Centre กว่า แต่ต้องเปลี่ยนสาย เดินจาก Chinatown ง่ายกว่า'],
        warn: 'ยังไม่ได้ยืนยันตัวอักษรทางออกสถานี Chinatown — ดูป้าย Maxwell / South Bridge Rd',
        status: 'tip', src: [SRC.hotel], maps: gdir(HOTEL, 'Maxwell Food Centre, Singapore') },
      { id: 'd2-ct', t: 'ev', s: '11:00', e: '13:00', icon: '🙏', title: 'มู + อาหารกลางวัน + กาแฟ', place: 'Chinatown', plan: '11:00–13:00', status: 'tip',
        detail: '<b>Ah Tai Hainanese Chicken Rice</b> — Maxwell Food Centre #01-07 · รีวิวระบุเปิด 11:00–19:30 ปิดวันอังคาร · ร้านในศูนย์อาหารส่วนใหญ่รับเงินสดเป็นหลัก <i>ยังไม่ยืนยันวิธีจ่ายของร้านนี้</i> พกเงินสดไว้<br><b>Buddha Tooth Relic Temple</b> — แหล่งที่พบระบุเวลาเปิดไม่ตรงกัน (07:00 หรือ 09:00 ถึง 17:00) ไปช่วง 11:00–13:00 อยู่ในเวลาเปิดทุกแหล่ง · งดเสื้อเปิดไหล่/กางเกง-กระโปรงสั้น มีผ้าคลุมให้ยืมหน้าวัด<br><b>ร้านกาแฟ: ยังไม่เลือก</b> — ตัวเลือกใกล้เส้นทาง (ยังไม่ตรวจเวลาเปิด): แผงโกปี๊ใน Maxwell Food Centre (ไม่ต้องเดินเพิ่ม) หรือ Nanyang Old Coffee บน South Bridge Rd',
        src: [SRC.ahtai, SRC.btrt],
        links: [
          { label: '📍 Ah Tai Chicken Rice', url: 'https://maps.app.goo.gl/WGd5i9JthquaSyqN9' },
          { label: '📍 Buddha Tooth Relic Temple', url: 'https://maps.app.goo.gl/xSocATh7DC4ESaws6' },
          { label: '☕ ค้นร้านกาแฟใกล้วัด', url: gsearch('coffee near Buddha Tooth Relic Temple Singapore') },
        ] },
      { id: 'd2-r2', t: 'rt', mm: [25, 40], title: 'Chinatown → Gate 2 → Singapore Flyer', from: 'Chinatown', to: 'Singapore Flyer (Zone 2)',
        leave: '13:00', leaveWhy: 'ตามแพลนเดิม 13:00–13:40 · แต่<b>ประตูสนามเปิด 14:15 วันเสาร์</b> ถ้าถึง 13:40 ต้องรอหน้าประตูราว 35 นาที (กลางแดด) จะออกช้ากว่านี้ 15–20 นาทีก็ยังทันประตูเปิด',
        total: '25–40 นาที', walk: '10–15 นาที', ride: 'ราว 8–10 นาที (4 สถานี)', buffer: 'รอรถ 3–5 นาที + คิวประตูตอนเปิด',
        steps: ['ขึ้น <b>Chinatown (DT19)</b> Downtown Line ฝั่งไป Expo', '<b>4 สถานี ลง Promenade (DT15)</b> ไม่ต้องเปลี่ยนสาย', 'ออก <b>ทางออก C</b> เดินไป <b>Gate 2 (Temasek Ave)</b>', 'เข้าสนามแล้วเดินตามทางใน Zone 2 ไป Singapore Flyer'],
        alt: ['ลง <b>Bayfront ทางออก E</b> (3 สถานี) เดิน 10 นาทีถึง <b>Gate 8 (Helix)</b> แล้วเดินต่อไป Flyer — เวลาเดินนี้เป็นตัวเลขทางการ'],
        status: 'ok', src: [SRC.lta, SRC.pwGuide, SRC.hours, SRC.map], maps: gdir('Chinatown MRT Station, Singapore', 'Promenade MRT Station Exit C, Singapore'), pin: 'g2' },
      { id: 'd2-flyer', t: 'ev', s: '14:00', e: '15:00', icon: '🎡', title: 'Singapore Flyer', place: 'Zone 2', plan: '14:00–15:00',
        official: { time: 'เปิดให้ผู้ถือบัตร 14:15–23:00 (รอบสุดท้าย 22:30)', note: 'ขึ้นก่อน 14:15 ไม่ได้ เพราะประตูสนามเปิด 14:15 · ฟรีสำหรับบัตร Zone 1-2 แบบมาก่อนได้ก่อน ขึ้นกับจำนวนที่รับได้' },
        status: 'ok', src: [SRC.flyer, SRC.flyerSite, SRC.hours], pin: 'flyer',
        detail: '<b>ผลต่อแพลน:</b> เริ่มต่อคิวได้เร็วสุด 14:15 · Flyer หมุนรอบละราว 30 นาที และ<b>ทางการไม่ได้บอกเวลารอคิว</b> ถ้าได้ขึ้น 14:30 จะลงราว 15:00 แล้วต้องเดินจาก Flyer (ด้านใต้ของ Zone 1) ไป Wharf Stage (ด้านเหนือ ใกล้ Gate 1) ซึ่งไกล — <b>น่าจะพลาดต้น Fan Forum 5–15 นาที หรือมากกว่าถ้าคิวยาว</b><br><b>ทางเลือก (ไม่ได้เปลี่ยนแพลนให้):</b> Flyer เปิดถึง 23:00 ย้ายไปขึ้นช่วงว่าง 15:40–16:30 ได้ แต่จะกินเวลาพักก่อน Sprint' },
      { id: 'd2-r3', t: 'rt', mm: [15, 25], title: 'Flyer → Wharf Stage (Zone 1)', from: 'Singapore Flyer', to: 'Zone 1 Wharf Stage',
        leave: '14:50', leaveWhy: 'Fan Forum เริ่ม 15:10 · ต้องเดินเกือบสุดความยาว Zone 1 ยังไม่มีเวลาเดินทางการ ประมาณ 15–25 นาที ถ้ายังไม่ได้ขึ้น Flyer ตอน 14:35 ให้เลือกว่าจะรอต่อหรือไป Fan Forum ก่อน',
        total: '15–25 นาที (ประมาณ)', walk: '15–25 นาที', ride: '—', buffer: 'คนเดินสวนช่วงประตูเพิ่งเปิด',
        steps: ['จาก Flyer เดินเข้า <b>Zone 1 (พื้นที่สีเหลืองบนแผนที่)</b> ตามทางเดินผู้ชม', 'เดินขึ้นเหนือผ่านด้านหลังอัฒจันทร์ฝั่งโค้ง 1–2', 'ถึง <b>F1 Village @ Zone 1</b> — Wharf Stage อยู่ถัดไป ใกล้ Gate 1'],
        warn: 'เส้นทางนี้อ่านจากแผนที่ทางการ ยังไม่เคยเดินจริง ถามเจ้าหน้าที่หน้างานว่าทางไหนสั้นสุด อย่าตัดผ่านพื้นที่ Paddock',
        status: 'unk', src: [SRC.map], pin: 'wharf' },
      { id: 'd2-ff', t: 'ev', s: '15:10', e: '15:40', icon: '🎙️', title: 'F1 Drivers’ Fan Forum', place: 'Zone 1 · Wharf Stage', plan: '15:10–15:40',
        official: { time: '15:10–15:40', note: 'ตรงกับแพลน' }, status: 'ok', src: [SRC.fanforum], pin: 'wharf',
        detail: 'ยืนกลางแดดบ่าย ทาครีมกันแดด ใส่หมวก' },
      { id: 'd2-rest1', t: 'rest', title: 'ช่วงว่าง 15:40–16:30 · พัก กิน เข้าห้องน้ำ เติมน้ำ',
        detail: 'อยู่ใน Zone 1 ต่อได้เลย มีร้านอาหาร ห้องน้ำ และจุดเติมน้ำใน F1 Village @ Zone 1 (ตามแผนที่ทางการ) · ควรไปถึงแท่นดูรถช่วงโค้ง 1–3 ราว <b>16:15–16:30</b> เพื่อหาที่ยืนก่อน Sprint 17:00', status: 'tip', src: [SRC.map] },
      { id: 'd2-r3b', t: 'rt', mm: [5, 15], title: 'Wharf Stage → แท่นโค้ง 1–3', from: 'Wharf Stage / F1 Village @ Zone 1', to: 'แท่น Walkabout ช่วงโค้ง 1–3',
        leave: '16:15', leaveWhy: 'Sprint เริ่ม 17:00 ไปถึงแท่นก่อน 30–45 นาทีเพื่อหาที่ยืน · แท่นไม่มีที่นั่งจองและไม่รับประกันตำแหน่ง',
        total: '5–15 นาที (ประมาณ)', walk: '5–15 นาที', ride: '—', buffer: 'หาที่ยืนบนแท่น',
        steps: ['จาก F1 Village @ Zone 1 เดินลงใต้ตามทางเดินผู้ชมไปทางโค้ง 1–3', 'มองหาป้าย Walkabout Viewing Platform (สัญลักษณ์รูปตาบนแผนที่)', 'อย่าขึ้น <b>Turn 1 Platform</b> — เป็นแท่นสำหรับผู้ใช้รถเข็น'],
        alt: ['ถ้าแท่นโค้ง 1–3 เต็ม: แท่น Pit Exit ที่อยู่ใกล้กัน'],
        warn: 'อ่านจากแผนที่ทางการ ยังไม่มีเวลาเดินที่ทางการระบุ', status: 'tip', src: [SRC.map, SRC.pwTicket], pin: 't13', spot: 't13' },
      { id: 'd2-sprint', t: 'ev', s: '17:00', e: '17:30', icon: '🏁', title: 'Formula 1 Sprint', place: 'จุดดูตั้งต้น: แท่น Walkabout โค้ง 1–3 (Zone 1)', plan: '17:00–17:30',
        official: { time: '17:00–17:30 (21 รอบ หรือไม่เกิน 60 นาที)', note: 'ตรงกับแพลน · ถ้ามีธงแดง/เซฟตี้คาร์อาจจบช้ากว่า 17:30' }, status: 'ok', src: [SRC.f1tt], spot: 't13', pin: 't13',
        detail: 'Sprint ครั้งแรกของสิงคโปร์ ออกตัวพร้อมกันทั้งกริด ช่วงโค้ง 1–3 เห็นรถเกาะกลุ่มในรอบแรก · จดในโน้ตว่าชอบมุมนี้ไหม ไว้ใช้เลือกจุดวันอาทิตย์' },
      { id: 'd2-r4', t: 'rt', mm: [30, 45], title: 'Zone 1 → Padang Stage (Zone 4)', from: 'โค้ง 1–3 (Zone 1)', to: 'Zone 4 Padang Stage',
        leave: '17:40', leaveWhy: 'Zara Larsson เริ่ม 18:45 มีเวลา 75 นาที ออกหลัง Sprint จบได้เลย ถึง Padang ราว 18:15–18:30 ยังเหลือเวลากินข้าวเย็นแถว F1 Village @ Zone 4',
        total: '30–45 นาที', walk: '30–45 นาที (ตามรายงานปีก่อน ๆ)', ride: '—', buffer: 'คนออกจากแท่นพร้อมกัน',
        steps: ['เดินตาม <b>Walking route Zone 1 to Zone 4</b> (เส้นประบนแผนที่ทางการ) ลงใต้ผ่านบริเวณ Flyer', 'เลียบ Raffles Avenue (Zone 3 สีชมพู) ไปทาง Esplanade', 'เข้า Zone 4 แถว Esplanade แล้วลอดทางลอดไป Padang'],
        alt: ['<b>นั่ง MRT (วิธีที่ทางการแนะนำ):</b> ออก Gate 1 → Nicoll Highway (ทางออก B) → Circle Line ลง <b>Esplanade ทางออก F</b> → เข้าใหม่ที่ Gate 3A/3B · เดินน้อยกว่า แต่ต้องตรวจกระเป๋าอีกรอบ'],
        warn: 'ทางการไม่ได้ระบุเวลาเดินข้ามโซน 30–45 นาทีเป็นตัวเลขจากผู้ชมปีก่อน',
        status: 'prev', src: [SRC.padang, SRC.map, SRC.out1], pin: 'padang' },
      { id: 'd2-zara', t: 'ev', s: '18:45', e: '19:45', icon: '🎤', title: 'ZARA LARSSON', place: 'Zone 4 · Padang Stage', plan: '18:45–19:45',
        official: { time: '18:45–19:45', note: 'ตรงกับแพลน' }, status: 'ok', src: [SRC.ent], pin: 'padang' },
      { id: 'd2-r5', t: 'rt', mm: [10, 15], title: 'Padang → Waterside (Zone 4)', from: 'Padang Stage', to: 'Waterside Stage',
        leave: '19:45', leaveWhy: 'HYO เริ่ม 20:05 มีเวลา 20 นาที อยู่ใน Zone 4 เหมือนกัน ออกทันทีที่ Zara จบ',
        total: '10–15 นาที (ประมาณ)', walk: '10–15 นาที', ride: '—', buffer: 'คนออกจาก Padang',
        steps: ['จาก Padang เดินลงทาง Connaught Drive ผ่าน Esplanade Park', 'Waterside อยู่ริมแม่น้ำ ใกล้ Anderson Bridge และโค้ง 11–12'],
        warn: 'อ่านจากแผนที่ทางการ ยังไม่มีเวลาเดินที่ทางการระบุ', status: 'tip', src: [SRC.map], pin: 'waterside' },
      { id: 'd2-hyo', t: 'ev', s: '20:05', e: '20:50', icon: '🎧', title: 'HYO', place: 'Zone 4 · Waterside', plan: '20:05–20:50',
        official: { time: '20:05–20:50', note: 'ตรงกับแพลน' }, status: 'ok', src: [SRC.ent], pin: 'waterside',
        detail: 'ถ้าอยากได้ที่ยืนบนแท่นโค้ง 11–12 สำหรับ Qualifying ควรไปราว 20:40 = <b>พลาดท้ายโชว์ HYO ประมาณ 10 นาที</b> ถ้าอยู่จนจบ 20:50 ยังทันเริ่ม 21:00 แต่อาจได้ที่ยืนแถวหลัง' },
      { id: 'd2-r5b', t: 'rt', mm: [3, 8], title: 'Waterside → แท่นโค้ง 11–12', from: 'Waterside Stage', to: 'แท่น Walkabout ช่วงโค้ง 11–12',
        leave: '20:40', leaveWhy: 'Qualifying เริ่ม 21:00 · ออก 20:40 ได้ที่ยืนดีกว่า แต่<b>พลาดท้ายโชว์ HYO ราว 10 นาที</b> · ออกตอนจบ 20:50 ยังทันเริ่ม แต่อาจได้ยืนแถวหลัง',
        total: '3–8 นาที (ประมาณ)', walk: '3–8 นาที', ride: '—', buffer: 'หาที่ยืนบนแท่น',
        steps: ['แท่นอยู่ติด Waterside ริมช่วงโค้ง 11 → 12 ก่อนขึ้น Anderson Bridge', 'อย่าขึ้น <b>Empress Platform</b> — เป็นแท่นสำหรับผู้ใช้รถเข็น'],
        alt: ['ถ้าเต็ม: แท่นริม Esplanade Drive (ช่วงโค้ง 13 → 14) ที่อยู่ถัดไป'],
        warn: 'อ่านจากแผนที่ทางการ ยังไม่มีเวลาเดินที่ทางการระบุ', status: 'tip', src: [SRC.map], pin: 't1112', spot: 't1112' },
      { id: 'd2-q', t: 'ev', s: '21:00', e: '22:40', icon: '🏎️', title: 'Formula 1 Qualifying', place: 'จุดดูตั้งต้น: โค้ง 11–12 (Zone 4)', plan: '21:00–22:40',
        official: { time: '21:00–22:00', note: 'แพลนเดิมเขียนจบ 22:40 แต่ทางการคือ 22:00 · ถ้านับตามแพลนเดิมจะซ้อนกับ The Killers 10 นาที แต่ตามเวลาทางการไม่ซ้อน มีเวลาเดินไป Padang 30 นาที · ถ้ามีธงแดงอาจจบช้ากว่า 22:00' },
        status: 'ok', src: [SRC.f1tt], spot: 't1112', pin: 't1112', endOfficial: '22:00' },
      { id: 'd2-r6', t: 'rt', mm: [10, 20], title: 'โค้ง 11–12 → Padang Stage', from: 'แท่นโค้ง 11–12', to: 'Padang Stage',
        leave: '22:00', leaveWhy: 'Qualifying จบ 22:00 ตามเวลาทางการ The Killers เริ่ม 22:30 · คนทั้ง Zone 4 จะไหลไป Padang พร้อมกัน ถ้าอยากได้ที่ใกล้เวที ต้องออกก่อนจบ Q3 ซึ่งเท่ากับพลาดช่วงชิงโพล',
        total: '10–20 นาที (ประมาณ)', walk: '10–20 นาที', ride: '—', buffer: 'คนแน่นมากช่วงนี้',
        steps: ['เดินย้อนผ่าน Esplanade Park / Connaught Drive ไป Padang'], warn: 'อ่านจากแผนที่ทางการ ยังไม่มีเวลาเดินที่ทางการระบุ',
        status: 'tip', src: [SRC.map], pin: 'padang' },
      { id: 'd2-killers', t: 'ev', s: '22:30', e: '23:45', icon: '🎸', title: 'THE KILLERS', place: 'Zone 4 · Padang Stage', plan: '22:30–23:45',
        official: { time: '22:30–23:45', note: 'ตรงกับแพลน' }, status: 'ok', src: [SRC.ent], pin: 'padang',
        detail: 'ยืนฝั่งที่ออกไปทางลอด A/B ได้ง่าย จะออก Gate 3A/3B ได้เร็วขึ้นตอนจบ' },
      { id: 'd2-back', t: 'ev', icon: '🏨', title: 'กลับโรงแรม', place: 'Hotel 81 Dickson', plan: 'หลัง The Killers', status: 'tip', ret: true,
        detail: 'โชว์จบ 23:45 · สนามปิด 00:00 · รถไฟเที่ยวสุดท้ายออกจาก City Hall 00:30 มีเวลา 45 นาทีสำหรับออกประตูและเข้าสถานี' },
      { id: 'd2-noodle', t: 'ev', icon: '🍜', title: 'Noodles at Night', place: 'ยังไม่ระบุร้าน', plan: 'หลังกลับโรงแรม', status: 'unk',
        detail: 'แพลนเดิมไม่ได้ระบุร้าน · มีแหล่งระบุว่า Ng Kuan Chilli Pan Mee สาขา Bencoolen เปิดถึงตี 5 (ยังไม่ยืนยัน) อยู่ห่างโรงแรมราว 700 ม.',
        src: [SRC.ngkuan], maps: gsearch('noodles open late near Hotel 81 Dickson Singapore'), mapsLabel: 'ค้นร้านก๋วยเตี๋ยวเปิดดึกใกล้โรงแรม' },
      { id: 'd2-sleep', t: 'ev', icon: '😴', title: 'พักผ่อน', place: 'Hotel 81 Dickson', plan: '—', status: 'tip' },
    ],
  },
  {
    id: 'd3', date: '2026-10-11', tab: 'Day 3', label: 'อาทิตย์ 11 ต.ค.', title: 'วัด · กาแฟ · Grand Prix · Lana Del Rey',
    items: [
      { id: 'd3-wake', t: 'ev', s: '09:00', e: '10:30', icon: '⏰', title: 'ตื่นและแต่งตัว', place: 'Hotel 81 Dickson', plan: '09:00–10:30', status: 'tip',
        detail: 'วันแข่งจริง ยืนยาวที่สุดในทริป พักขาช่วงเช้าให้มากที่สุด' },
      { id: 'd3-r1', t: 'rt', mm: [10, 20], title: 'โรงแรม → Kwan Im Thong Hood Cho Temple', from: 'Hotel 81 Dickson', to: 'Kwan Im Thong Hood Cho Temple (178 Waterloo St)',
        leave: '11:30', leaveWhy: 'ตามแพลนเดิม 11:30–12:00 · ใช้จริงราว 10–20 นาที',
        total: '10–20 นาที', walk: '10–15 นาที (เดินทั้งเส้น ราว 700 ม. ประมาณจากพิกัด)', ride: '—', buffer: '—',
        steps: ['เดินจากโรงแรมไป Waterloo Street — ใกล้พอที่จะไม่ต้องขึ้นรถ'],
        alt: ['ไม่อยากเดิน: Jalan Besar → Downtown Line <b>1 สถานี ลง Bencoolen (DT21)</b> แล้วเดินต่อราว 300 ม.'],
        status: 'tip', maps: gdir(HOTEL, 'Kwan Im Thong Hood Cho Temple, 178 Waterloo St, Singapore', 'walking') },
      { id: 'd3-temple', t: 'ev', s: '12:00', e: '13:00', icon: '🙏', title: 'มูและอาหารกลางวัน', place: 'Waterloo St / Bencoolen St', plan: '12:00–13:00', status: 'tip',
        detail: '<b>Kwan Im Thong Hood Cho Temple</b> — แหล่งที่พบระบุเปิด 06:00–18:00 ทุกวัน · แต่งกายสุภาพ<br><b>Ng Kuan Chilli Pan Mee Bencoolen</b> — 131 Bencoolen St ห่างจากวัดราว 150 ม. · <i>ยังไม่ยืนยันเวลาเปิดช่วงกลางวันและวิธีจ่ายเงิน</i> พกเงินสดไว้',
        src: [SRC.kwanim, SRC.ngkuan],
        links: [
          { label: '📍 Kwan Im Thong Hood Cho', url: 'https://maps.app.goo.gl/54bFZCm4WN6H3Xir5' },
          { label: '📍 Ng Kuan Chilli Pan Mee', url: 'https://maps.app.goo.gl/pY3UmzCacztX48J16' },
        ] },
      { id: 'd3-free', t: 'ev', s: '12:30', e: '14:20', icon: '☕', title: 'Coffee / Free time', place: 'Tiong Bahru Bakery (Fort Canning) · Asian Civilisations Museum', plan: '12:30–14:20', status: 'unk',
        overlap: 'แพลนเดิมให้ช่วงนี้เริ่ม 12:30 ซ้อนกับ “มูและอาหารกลางวัน” ที่จบ 13:00 อยู่ 30 นาที — คงเวลาไว้ตามเดิม ไม่ได้แก้ให้',
        detail: '<b>ลิงก์เดิมในแพลน</b> เปิดแล้วเป็นเส้นทาง Google Maps: โรงแรม → วัดกวนอิม → Ng Kuan → Fort Canning MRT → Asian Civilisations Museum → สนาม F1 (ไม่ใช่สถานที่เดียว)<br><b>Tiong Bahru Bakery Foothills</b> — 70 River Valley Rd ใน Fort Canning Park · รีวิวระบุเปิด 07:30–19:00<br><b>Asian Civilisations Museum</b> — 1 Empress Place อยู่ติด Gate 4 (Empress) ของสนาม · เวลาปกติ 10:00–19:00 แต่<b>ยังไม่พบประกาศว่าเปิดตามปกติช่วง F1 หรือไม่</b><br><b>เวลาไม่น่าพอทั้งสองที่:</b> ถ้ากินข้าวเสร็จ 13:00 จะเหลือ 80 นาทีสำหรับเดินทาง 2 ช่วง + กาแฟ + พิพิธภัณฑ์ เลือกอย่างใดอย่างหนึ่งจะไม่รีบ',
        src: [SRC.tbb],
        links: [
          { label: '🗺️ เส้นทางเดิมในแพลน', url: 'https://maps.app.goo.gl/mWrZekCssbAXJXsD7' },
          { label: '📍 Tiong Bahru Bakery Foothills', url: gsearch('Tiong Bahru Bakery Foothills, 70 River Valley Rd, Singapore') },
          { label: '📍 Asian Civilisations Museum', url: gsearch('Asian Civilisations Museum, 1 Empress Pl, Singapore') },
        ] },
      { id: 'd3-r2', t: 'rt', mm: [25, 40], title: 'Bencoolen → Fort Canning → Gate 4 (Empress)', from: 'Ng Kuan / Bencoolen St', to: 'Zone 4 ทาง Gate 4 (Empress)',
        leave: '14:20', leaveWhy: 'แพลนเดิมให้ 14:20–15:00 เดินทางไปสนาม · <b>ประตูเปิด 15:00 วันอาทิตย์</b> และ Porsche เริ่ม 15:40 ถึงก่อน 15:00 ต้องรอหน้าประตู',
        total: '25–40 นาที', walk: '15–25 นาที', ride: '2–3 นาที (1 สถานี)', buffer: 'คิวประตูตอนเปิด 5–15 นาที',
        steps: [
          'ไปร้านกาแฟ: <b>Bencoolen (DT21)</b> → Downtown Line ฝั่งไป Expo <b>1 สถานี ลง Fort Canning (DT20)</b>',
          'จาก Fort Canning เดินลงไปทางแม่น้ำ → Asian Civilisations Museum / <b>Gate 4 (Empress)</b> ราว 1 กม. (ประมาณจากพิกัด)',
          'เข้า Gate 4 แล้วอยู่ใน Zone 4 ติดโค้ง 11–12 และ Waterside',
        ],
        alt: ['นั่ง MRT ไป <b>Raffles Place ทางออก A หรือ B</b> แล้วเดิน 10 นาทีถึง Gate 4/5/6 (ตัวเลขทางการ)', 'ถ้าจะดูเรซที่โค้ง 1–3: ไป <b>Nicoll Highway ทางออก B</b> เดิน 7 นาทีถึง Gate 1 (ตัวเลขทางการ) แทน'],
        warn: 'ถนนรอบ Padang ปิดช่วง F1 ทางเดินจาก Fort Canning ถึง Gate 4 อาจต้องอ้อมตามป้าย อย่ายึดเส้นทางใน Google Maps',
        status: 'ok', src: [SRC.z4Guide, SRC.hours, SRC.lta, SRC.map], maps: gdir('Fort Canning MRT Station, Singapore', 'Asian Civilisations Museum, 1 Empress Pl, Singapore', 'walking'), pin: 'g4' },
      { id: 'd3-porsche', t: 'ev', s: '15:40', e: '16:15', icon: '🏎️', title: 'Porsche Carrera Cup Asia · Second Race', place: 'ดูจากแท่นใกล้ประตูที่เข้า', plan: '15:40–16:15',
        official: { time: '15:40–16:15', note: 'ตรงกับแพลน' }, status: 'ok', src: [SRC.f1tt], spot: 't1112', pin: 't1112',
        detail: 'ใช้รอบนี้ลองมุมจริงก่อนเรซใหญ่ คนยังน้อย เดินดูได้ว่าแท่นไหนรั้วบังน้อย' },
      { id: 'd3-rest1', t: 'rest', title: 'ช่วงว่าง 16:15–18:00 · ตัดสินใจจุดดูเรซ + กินข้าวเย็น',
        detail: 'เป็นช่วงพักยาวสุดของวัน กินข้าว เข้าห้องน้ำ เติมน้ำให้เต็มขวด · <b>ต้องเลือกตอนนี้ว่าจะดูเรซที่ไหน</b> (ดูหน้า “จุดดู F1”) ถ้าเลือกโค้ง 1–3 ต้องเริ่มเดินไป Zone 1 ราว 16:30–17:00 · แท่นยอดนิยมมีคนจองที่ตั้งแต่ก่อน Drivers’ Parade', status: 'tip', src: [SRC.map] },
      { id: 'd3-parade', t: 'ev', s: '18:00', e: '18:30', icon: '👋', title: 'Formula 1 Drivers’ Parade', place: 'รอบสนาม — ดูจากแท่นที่เลือก', plan: '18:00–18:30',
        official: { time: '18:00–18:30', note: 'ตรงกับแพลน' }, status: 'ok', src: [SRC.f1tt],
        detail: 'นักแข่งนั่งรถวนรอบสนามช้า ๆ เห็นได้จากทุกแท่นริมแทร็ก ไม่ต้องย้ายที่ · หลังจบถึง 19:44 ถ้าออกจากแท่นอาจเสียที่ ผลัดกันไปห้องน้ำ' },
      { id: 'd3-anthem', t: 'ev', s: '19:44', e: '19:46', icon: '🇸🇬', title: 'National Anthem', place: 'กริดสตาร์ต', plan: '19:44–19:46',
        official: { time: '19:44–19:46', note: 'ตรงกับแพลน' }, status: 'ok', src: [SRC.f1tt],
        detail: 'พิธีอยู่ที่กริดหน้าพิท จากแท่น Walkabout จะได้ยินเสียง <i>ยังไม่ยืนยันว่ามีจอให้ดูจากแท่นที่เลือก</i>' },
      { id: 'd3-race', t: 'ev', s: '20:00', e: '22:00', icon: '🏆', title: 'Formula 1 Singapore Grand Prix', place: 'เลือก A: โค้ง 1–3 (Zone 1) หรือ B: Memorial / Zone 4', plan: '20:00–22:00',
        official: { time: '20:00–22:00 (62 รอบ หรือไม่เกิน 120 นาที)', note: 'ตรงกับแพลน · เรซอาจจบก่อน 22:00 ถ้าไม่มีเซฟตี้คาร์ หรือลากถึง 22:00 ถ้ามี' }, status: 'ok', src: [SRC.f1tt], spot: 't13', pin: 't13',
        detail: '<b>A · โค้ง 1–3 (เน้นมุมเรซ)</b> — ถ้าเรซจบ 22:00 ต้องเดินข้ามโซน 30–45 นาทีในฝูงคนหลังเรซ <b>น่าจะถึง Padang 22:35–22:50 หรือช้ากว่า = พลาดต้นโชว์ LANA อย่างน้อย 10–25 นาที</b> และได้ที่ยืนไกลเวที<br><b>B · Memorial / Zone 4 (เน้นเดินน้อย)</b> — เดินไป Padang 8–15 นาที ทันเริ่ม 22:25 แต่มุมรถจำกัดกว่า<br>ดูตารางเทียบเต็มในหน้า “จุดดู F1”' },
      { id: 'd3-r3', t: 'rt', mm: [8, 15], title: 'จุดดูเรซ → Padang Stage', from: 'โค้ง 1–3 (A) หรือ Memorial (B)', to: 'Zone 4 Padang Stage',
        leave: '22:00', leaveWhy: 'LANA DEL REY เริ่ม 22:25 · จาก Memorial ออกหลังธงตาหมากรุกยังทัน · จากโค้ง 1–3 ถ้าจะทันเพลงแรกต้องออกราว 21:40 = <b>พลาดช่วงท้ายเรซประมาณ 20 นาที</b> (ถ้าเรซวิ่งเต็มเวลา)',
        total: 'B: 8–15 นาที · A: 30–45 นาทีขึ้นไป', walk: 'ตามด้านซ้าย', ride: '—', buffer: 'คนทั้งสนามเดินไป Padang พร้อมกัน',
        steps: ['<b>จาก Memorial (B):</b> ลอดทางลอด A/B ใกล้โค้ง 8 เข้า Padang', '<b>จากโค้ง 1–3 (A):</b> เดินตาม Walking route Zone 1 → Zone 4 ผ่าน Flyer และ Raffles Avenue', '<b>Track Walk:</b> ทางการเปิดให้ผู้ชม Zone 1-2 เดินบนแทร็กไป Padang ราว 25 นาทีหลังตรวจความปลอดภัยเสร็จ — สนุก แต่ช้ากว่าและไม่รู้เวลาเปิดแน่นอน'],
        alt: ['<b>MRT (ทางการแนะนำ):</b> Gate 1 → Nicoll Highway → Circle Line ลง Esplanade ทางออก F → เข้า Gate 3A/3B ใหม่ · สถานีหลังเรซคนแน่นมาก ไม่รับประกันว่าเร็วกว่าเดิน'],
        warn: 'ไม่มีเส้นทางไหนรับประกันว่าทันต้นโชว์จาก Zone 1 · เวลาเดินข้ามโซนเป็นตัวเลขจากผู้ชมปีก่อน',
        status: 'prev', src: [SRC.padang, SRC.trackwalk, SRC.map], pin: 'padang' },
      { id: 'd3-lana', t: 'ev', s: '22:25', e: '23:55', icon: '🎤', title: 'LANA DEL REY', place: 'Zone 4 · Padang Stage', plan: '22:25–23:55',
        official: { time: '22:25–23:55', note: 'ตรงกับแพลน' }, status: 'ok', src: [SRC.ent], pin: 'padang',
        detail: 'โชว์จบ 23:55 สนามปิด 00:00 · คืนนี้คนออกพร้อมกันมากที่สุดของงาน' },
      { id: 'd3-back', t: 'ev', icon: '🏨', title: 'กลับโรงแรม', place: 'Hotel 81 Dickson', plan: 'หลัง LANA DEL REY', status: 'tip', ret: true,
        detail: 'รถไฟเที่ยวสุดท้ายออกจาก City Hall <b>00:45</b> คืนนี้ มีเวลา 50 นาทีหลังโชว์จบ · ถ้าคิวเข้าสถานียาวเกิน 30 นาที เดินกลับโรงแรม 20–30 นาทีแน่นอนกว่า' },
      { id: 'd3-noodle', t: 'ev', icon: '🍜', title: 'Noodles at Night', place: 'ยังไม่ระบุร้าน', plan: 'หลังกลับโรงแรม', status: 'unk',
        detail: 'ดูหมายเหตุเดียวกับคืนวันเสาร์', maps: gsearch('noodles open late near Hotel 81 Dickson Singapore'), mapsLabel: 'ค้นร้านก๋วยเตี๋ยวเปิดดึกใกล้โรงแรม' },
      { id: 'd3-sleep', t: 'ev', icon: '😴', title: 'พักผ่อน', place: 'Hotel 81 Dickson', plan: '—', status: 'tip' },
    ],
  },
  {
    id: 'd4', date: '2026-10-12', tab: 'Day 4', label: 'จันทร์ 12 ต.ค.', title: 'เก็บกระเป๋า · Brunch · บินกลับ',
    items: [
      { id: 'd4-wake', t: 'ev', s: '10:00', e: '12:00', icon: '🧳', title: 'ตื่นและเก็บกระเป๋า', place: 'Hotel 81 Dickson', plan: '10:00–12:00', status: 'tip',
        detail: 'เช็กพาสปอร์ต บัตร และของในตู้เซฟ/ห้องน้ำ' },
      { id: 'd4-co', t: 'ev', s: '12:00', e: '12:30', icon: '🏨', title: 'Check-out', place: 'Hotel 81 Dickson', plan: '12:00–12:30', status: 'tip',
        detail: 'ถามโรงแรมว่าฝากกระเป๋าระหว่างไป Brunch ได้ไหม <i>ยังไม่ยืนยัน</i>' },
      { id: 'd4-brunch', t: 'ev', s: '12:30', e: '14:00', icon: '🥐', title: 'Brunch + Coffee', place: 'ยังไม่ระบุร้าน', plan: '12:30–14:00', status: 'unk',
        detail: 'แพลนเดิมไม่ได้ระบุร้าน เลือกร้านใกล้โรงแรมหรือใกล้สถานี Jalan Besar จะไม่ต้องลากกระเป๋าไกล',
        maps: gsearch('brunch cafe near Jalan Besar MRT Singapore'), mapsLabel: 'ค้นร้าน Brunch ใกล้ Jalan Besar' },
      { id: 'd4-r1', t: 'rt', mm: [45, 60], title: 'โรงแรม → Changi T2', from: 'Hotel 81 Dickson', to: 'Changi Airport T2',
        leave: '14:00', leaveWhy: 'ตามแพลนเดิม 14:00–15:00 · ถึงสนามบินราว 15:00 ก่อนเครื่องออก 18:15 มากกว่า 3 ชั่วโมง',
        total: '45–60 นาที', walk: '8–12 นาที', ride: 'ราว 35–40 นาที', buffer: 'รอรถ/เปลี่ยนขบวน 5–10 นาที',
        steps: ['<b>Jalan Besar (DT22)</b> → Downtown Line ฝั่งไป Expo', 'นั่งยาวถึง <b>Expo (DT35)</b> ปลายสาย', 'เปลี่ยนขบวนไป <b>Changi Airport (CG2)</b> 1 สถานี', 'เดินตามป้ายไป Terminal 2'],
        alt: ['แท็กซี่/Grab จากโรงแรม — ถนนรอบ Marina Bay ทยอยเปิดถึงเช้า 13 ต.ค. อาจมีรถติดบางช่วง'],
        status: 'tip', src: [SRC.ltaNews], maps: gdir(HOTEL, 'Changi Airport Terminal 2, Singapore') },
      { id: 'd4-ci', t: 'ev', s: '15:00', e: '16:00', icon: '🛄', title: 'ช่วง Check-in + Boarding (ตามแพลนต้นฉบับ)', place: 'Changi Airport T2', plan: '15:00–16:00', status: 'unk',
        detail: 'แพลนเดิมเขียนช่วงนี้ถึง 16:00 แต่<b>เวลา Boarding จริงขึ้นกับเที่ยวบิน</b> เครื่องออก 18:15 ปกติเรียกขึ้นเครื่องช้ากว่า 16:00 มาก — ดูเวลาและประตูบน boarding pass และจอสนามบิน อย่ายึด 16:00' },
      { id: 'd4-fly', t: 'ev', s: '18:15', e: '20:35', icon: '✈️', title: 'เที่ยวบินกลับ BKK', place: 'Changi T2 → BKK', plan: '18:15 (เวลาสิงคโปร์) – 19:35 (เวลาไทย)', status: 'tip',
        detail: 'เวลาออก 18:15 เป็นเวลาสิงคโปร์ · เวลาถึง 19:35 เป็นเวลาไทย · ช่วงนี้คือเวลาบิน ไม่ใช่เวลาที่ต้องอยู่สนามบิน' },
    ],
  },
];

/* จุดดูรถ */
const SPOTS = [
  { id: 't7', name: 'Memorial · โค้ง 7–8', zone: 4, tags: ['easy'], uses: 'ศุกร์ Sprint Qualifying · ตัวเลือก B วันอาทิตย์', pin: 't7',
    img: { url: 'https://p16-lemon8-sign-sg.tiktokcdn.com/tos-alisg-v-a3e477-sg/ow57DfwG9ElQIknHDAmgFCfvEEt5EA1BDBaAhU~tplv-sdweummd6v-share_card_play.jpeg?lk3s=66c60501&source=share_card&x-expires=1793793600&x-signature=s4UIOOSzlCQQCQRg7V5QQC0hB64%3D',
      year: 2024, credit: 'StarklyPositive (Lemon8)', page: 'https://www.lemon8-app.com/@starklypositive/7417320491767087633?region=sg', pageLabel: '▶️ ดูวิดีโอต้นฉบับ 38 วินาที',
      cap: 'ภาพปกวิดีโอจากผู้ถือบัตร Zone 4 Walkabout เข้า Gate 3B เจ้าของโพสต์ระบุว่าเป็นโค้ง 7 ฝั่งตรงข้าม Suntec · มุมระดับพื้น มีแผงกั้นเหล็กและรั้วตาข่ายสูงอยู่ด้านหน้า เห็นรถผ่านหลังกำแพงคอนกรีต · ตำแหน่งแท่นปี 2026 อาจไม่ตรงกับจุดนี้' },
    sees: 'รถมาจากทางตรง Raffles Boulevard เบรกเข้าโค้งซ้าย 7 แล้วเร่งไปโค้ง 8 (อ่านจากผังสนาม ไม่ใช่จากภาพจริง)',
    near: 'แท่นอยู่ริมแทร็ก ระยะจริงยังไม่ยืนยัน', block: 'วิดีโอปี 2024 เห็นแผงกั้นเหล็ก รั้วตาข่ายสูง และกำแพงคอนกรีตอยู่ระหว่างคนดูกับแทร็ก — บันทึกผู้ชมปี 2025 บอกว่าใน Zone 4 เลี่ยงรั้วแทบไม่ได้',
    screen: 'ยังไม่ยืนยันว่ามีจอ', crowd: 'ปี 2025 มีรายงานว่าแท่นตรงข้าม Stamford Grandstand คนแน่นมาก',
    pros: 'ใกล้ Gate 3A/3B และ Padang ที่สุด เดินน้อย กลับโรงแรมง่าย', cons: 'เห็นรถช่วงสั้น ถ้าไม่มีจอจะตามอันดับไม่ได้',
    next: 'ไป Padang Stage 8–15 นาที (ลอดทางลอด A/B)', full: 'แท่นริม Raffles Avenue ใกล้ Gate 7 (โค้ง 14–15)',
    rest: 'นั่งพักบนขั้นแท่นได้ก่อนเริ่ม พอรถวิ่งเจ้าหน้าที่จะให้ยืน (ประสบการณ์ปี 2025)',
    src: [{ ...SRC.map, st: 'ok' }, { ...SRC.lemon, st: 'prev' }, { ...SRC.note, st: 'prev' }, { ...SRC.shaun, st: 'unk', extra: 'ลิงก์จากบรีฟ เปิดอ่านซ้ำไม่สำเร็จตอนตรวจ' }] },
  { id: 't13', name: 'โค้ง 1–3', zone: 1, tags: ['race'], uses: 'เสาร์ Sprint · ตัวเลือก A วันอาทิตย์', pin: 't13',
    img: { url: 'https://flyf1travel.com/wp-content/uploads/2025/10/3-1024x538.jpg', year: 2025, credit: 'Fly F1 Travel', cap: 'จากปลายแท่น Walkabout ฝั่งโค้ง 3 ไม่ใช่มุมตรงหน้าโค้ง 1 เห็นบริเวณโค้งต่อเนื่อง มีรั้วและเสาบัง' },
    sees: 'รถเข้าโค้ง เปลี่ยนทิศ และออกโค้งต่อเนื่องช่วงโค้ง 1–3 · รอบแรกรถเกาะกลุ่ม', near: 'ปานกลาง — จากภาพปี 2025 รถอยู่ห่างออกไปอีกฝั่งของแทร็ก',
    block: 'รั้วตาข่ายและเสารั้วอยู่ในเฟรม', screen: 'ยังไม่ยืนยันว่ามีจอ', crowd: 'เป็นจุดยอดนิยมของ Premier Walkabout คาดว่าแน่นช่วงสตาร์ต (ยังไม่มีตัวเลข)',
    pros: 'เห็นการแข่งมากที่สุดในกลุ่มจุดที่เลือก โดยเฉพาะรอบแรกและรถออกจากพิท', cons: 'ไกลจาก Padang และโรงแรมที่สุด',
    next: 'ไป Padang Stage 30–45 นาทีขึ้นไป (ตัวเลขจากผู้ชมปีก่อน)', full: 'แท่น Pit Exit ที่อยู่ใกล้กัน หรือแท่นช่วงโค้ง 5',
    rest: 'ไม่มีที่นั่งจอง ระหว่างเซสชันต้องยืน', src: [{ ...SRC.fly, st: 'prev' }, { ...SRC.pwTicket, st: 'ok' }, { ...SRC.map, st: 'ok' }] },
  { id: 't1112', name: 'โค้ง 11–12 · Anderson Bridge', zone: 4, tags: ['easy'], uses: 'เสาร์ Qualifying · อาทิตย์ Porsche', pin: 't1112',
    img: null, noImg: 'ยังไม่มีภาพมุมจริงจากแท่น Walkabout ที่ตรวจปีและจุดถ่ายได้',
    sees: 'โค้งแคบความเร็วต่ำต่อกัน รถเบรก เลี้ยว และเปลี่ยนทิศก่อนขึ้นสะพาน (อ่านจากผังสนาม)', near: 'ช่วงนี้แทร็กแคบ รถน่าจะใกล้ ระยะจริงยังไม่ยืนยัน',
    block: 'รั้วตาข่าย · มีอัฒจันทร์ Empress และแท่นผู้ใช้รถเข็น (Empress Platform) อยู่ใกล้ — แท่นนั้นไม่ใช่ของบัตรนี้', screen: 'ยังไม่ยืนยันว่ามีจอ',
    crowd: 'ผู้ชมปี 2025 หลายคนบ่นว่าโค้ง 12 และจุดยอดนิยมแน่นมาก (สรุปจากกระทู้ Reddit ตามบรีฟ)',
    pros: 'ติด Waterside และ Gate 4 เดินต่อจาก HYO ได้ทันที', cons: 'ความเร็วต่ำ เห็นช่วงสั้น คนแน่น',
    next: 'ไป Padang Stage 10–20 นาที', full: 'แท่นริม Esplanade Drive (ช่วงโค้ง 13 → 14) ที่อยู่ถัดไป — มีภาพจริงในการ์ดด้านล่าง',
    rest: 'Esplanade Park อยู่ติดกัน มีร้านอาหารและห้องน้ำตามแผนที่', src: [{ ...SRC.map, st: 'ok' }, { ...SRC.reddit1, st: 'prev', extra: 'เปิดอ่านซ้ำไม่ได้ตอนตรวจ ใช้สรุปจากบรีฟ' }] },
  { id: 'pit', name: 'Pit Exit', zone: 1, tags: ['race'], uses: 'ตัวเลือกสำรองฝั่ง Zone 1', pin: 't13',
    img: { url: 'https://flyf1travel.com/wp-content/uploads/2025/10/1-1-1024x538.jpg', year: 2025, credit: 'Fly F1 Travel', cap: 'จากแท่น Walkabout ใกล้ทางออกพิท รถใกล้ แต่รั้วอยู่ตรงหน้า' },
    sees: 'รถออกจากพิทและรถที่วิ่งผ่านช่วงโค้ง 1', near: 'ใกล้ — จากภาพปี 2025', block: 'รั้วตาข่ายและเสาอยู่ตรงหน้าเต็มเฟรม', screen: 'ยังไม่ยืนยันว่ามีจอ',
    crowd: 'ยังไม่มีข้อมูล', pros: 'เห็นรถใกล้และจังหวะเข้าพิทช่วงเรซ', cons: 'รั้วบังมาก เห็นการแข่งบนแทร็กน้อยกว่าโค้ง 1–3',
    next: 'ไป Padang Stage 30–45 นาทีขึ้นไป', full: 'แท่นโค้ง 1–3', rest: 'ไม่มีที่นั่งจอง', src: [{ ...SRC.fly, st: 'prev' }, { ...SRC.pwTicket, st: 'ok' }] },
  { id: 't5', name: 'ทางออกโค้ง 5', zone: 1, tags: ['race'], uses: 'ตัวเลือกชมรถอีกแบบ', pin: 't5',
    img: { url: 'https://flyf1travel.com/wp-content/uploads/2025/10/6-1024x538.jpg', year: 2025, credit: 'Fly F1 Travel', cap: 'มองตามท้ายรถที่เร่งออกจากโค้ง 5 ไปตามทางตรงโค้ง 5–6 ไม่ใช่ภาพที่เห็นทั้งโค้ง มีรั้วบังเด่น' },
    sees: 'ท้ายรถตอนเร่งออกจากโค้ง 5 ไปตามทางตรง', near: 'ใกล้ แต่เห็นจากด้านหลัง', block: 'ซี่รั้วเหล็กบังเด่นในภาพปี 2025', screen: 'ยังไม่ยืนยันว่ามีจอ',
    crowd: 'ยังไม่มีข้อมูล', pros: 'ได้ยินเสียงเร่งเครื่องเต็ม ๆ ใกล้ Gate 2 และ Promenade MRT', cons: 'ไม่เห็นการแซง ไม่เห็นทั้งโค้ง',
    next: 'ไป Padang Stage ราว 25–40 นาที (ประมาณ)', full: 'เดินต่อไปแท่นโค้ง 1–3 หรือกลับ Zone 4', rest: 'ไม่ต้องเดินไปเพื่อใช้บัตรให้คุ้ม ถ้าไม่ได้ผ่านทางนี้',
    src: [{ ...SRC.fly, st: 'prev' }, { ...SRC.pwTicket, st: 'ok' }] },
  { id: 't1314', name: 'Esplanade Drive · ระหว่างโค้ง 13–14', zone: 4, tags: ['easy'], uses: 'ที่หลบเมื่อแท่นโค้ง 11–12 เต็ม', pin: 't1314',
    img: { url: 'https://assets.st-note.com/img/1787224834-vRAGaWBPbErDmoyLMVTfOxZ7.jpg?width=1200', year: 2025, credit: 'torazou_iced_latte (note.com)', page: SRC.note.url, pageLabel: 'เปิดบันทึกต้นฉบับ ↗',
      cap: 'แท่น Walkabout เตี้ย ๆ ริมแทร็กช่วงกลางระหว่างโค้ง 13 กับ 14 ฝั่งตะวันออกเฉียงใต้ ถ่ายตอนกลางวันโดยผู้ถือบัตร Zone 4 Walkabout · แทร็กอยู่ติดแท่น มีรั้วตาข่ายคั่น ด้านหลังเป็นตึก Fullerton' },
    sees: 'รถเร่งผ่านทางตรงบน Esplanade Drive อย่างเดียว ไม่เห็นโค้ง (เจ้าของภาพบอกว่า “แค่วิ่งผ่านทางตรง”)', near: 'ใกล้มาก — จากภาพปี 2025 แท่นอยู่ติดขอบแทร็ก',
    block: 'รั้วตาข่ายสูงตลอดแนว แท่นค่อนข้างเตี้ย', screen: 'ยังไม่ยืนยันว่ามีจอ', crowd: 'ภาพปี 2025 ช่วงกลางวันคนยังนั่งพักบนขั้นได้ ยังไม่มีข้อมูลช่วงเรซ',
    pros: 'รถผ่านใกล้และเร็ว อยู่ระหว่าง Waterside กับ Esplanade เดินถึงง่าย', cons: 'เห็นแค่ช่วงทางตรง รถผ่านแวบเดียว',
    next: 'ไป Padang Stage ราว 10–15 นาที (ประมาณ)', full: 'เดินต่อไปแท่นช่วงโค้ง 14–15 ริม Raffles Avenue', rest: 'ก่อนเริ่มนั่งบนขั้นได้ พอรถวิ่งเจ้าหน้าที่ให้ยืน (ปี 2025)',
    src: [{ ...SRC.note, st: 'prev' }, { ...SRC.map, st: 'ok' }] },
  { id: 't1415', name: 'Raffles Avenue ใกล้ Gate 7 · โค้ง 14–15', zone: 4, tags: ['easy'], uses: 'ที่หลบเมื่อแท่นอื่นใน Zone 4 เต็ม', pin: 't1415',
    img: { url: 'https://assets.st-note.com/img/1787224942-CU1ZtfzjnpuVwDhJbQxs8X4E.jpg?width=1200', year: 2025, credit: 'torazou_iced_latte (note.com)', page: SRC.note.url, pageLabel: 'เปิดบันทึกต้นฉบับ ↗',
      cap: 'ตัวแท่น Walkabout แบบขั้นบันไดช่วงโค้ง 14–15 ฝั่งตะวันออก ถ่ายตอนกลางวันโดยผู้ถือบัตร Zone 4 Walkabout · แทร็กอยู่หลังรั้วและแนวต้นไม้ทางซ้าย · เจ้าของภาพบอกว่าขั้นบนสุดคนแย่งกัน ช่วงต้นเรซแน่นแล้วค่อย ๆ ว่าง' },
    sees: 'รถวิ่งผ่านช่วงโค้ง 14 → 15 ริม Esplanade', near: 'ยังไม่ยืนยัน', block: 'รั้วตาข่าย — ผู้ชมปี 2025 บอกเลี่ยงแทบไม่ได้', screen: 'ผู้ชมปี 2025 (บัตร Zone 4 Walkabout) บอกว่าโซน Walkabout ส่วนใหญ่ไม่มีจอ',
    crowd: 'ผู้ชมปี 2025 เรียกจุดหน้า Gate 7 ว่าหาที่ง่ายกว่าจุดอื่น', pros: 'คนน้อยกว่า อยู่ติด Gate 7', cons: 'ไกล Padang กว่า Memorial เล็กน้อย',
    next: 'ไป Padang Stage ราว 10–20 นาที (ประมาณ)', full: 'เดินเลียบ Raffles Avenue หาแท่นถัดไป', rest: 'ก่อนเริ่มนั่งได้ พอรถวิ่งเจ้าหน้าที่ให้ยืน (ปี 2025)',
    src: [{ ...SRC.note, st: 'prev' }, { ...SRC.map, st: 'ok' }] },
];

/* หมุดบนแผนที่ทางการ — พิกัดเป็น % ของภาพ อ่านจากป้ายบนแผนที่เอง (ตำแหน่งโดยประมาณ) */
const PINS = [
  { id: 'g1', k: 'gate', name: 'Gate 1 · Republic Blvd', x: 86.9, y: 31.7, info: 'Nicoll Highway MRT ทางออก B เดิน 7 นาที' },
  { id: 'g2', k: 'gate', name: 'Gate 2 · Temasek Ave', x: 65.0, y: 55.7, info: 'Promenade MRT ทางออก C' },
  { id: 'g3a', k: 'gate', name: 'Gate 3A / 3B · Stamford', x: 33.2, y: 20.3, info: 'City Hall ทางออก A เดิน 5–10 นาที · Esplanade ทางออก F' },
  { id: 'g4', k: 'gate', name: 'Gate 4 · Empress', x: 5.3, y: 44.6, info: 'Raffles Place ทางออก A/B เดิน 10 นาที' },
  { id: 'g7', k: 'gate', name: 'Gate 7 · Marina Square', x: 36.5, y: 41.0, info: 'City Hall ทางออก A · Esplanade ทางออก C' },
  { id: 'g8', k: 'gate', name: 'Gate 8 · Helix', x: 48.7, y: 85.1, info: 'Bayfront ทางออก E เดิน 10 นาที' },
  { id: 'padang', k: 'stage', name: 'Padang Stage (Zone 4)', x: 20.0, y: 28.0, info: 'CORTIS · ZARA LARSSON · THE KILLERS · LANA DEL REY' },
  { id: 'waterside', k: 'stage', name: 'Waterside (Zone 4)', x: 12.4, y: 47.5, info: 'HYO' },
  { id: 'wharf', k: 'stage', name: 'Wharf Stage (Zone 1)', x: 92.2, y: 24.9, info: 'F1 Drivers’ Fan Forum' },
  { id: 'flyer', k: 'stage', ic: '🎡', name: 'Singapore Flyer (Zone 2)', x: 67.9, y: 76.1, info: 'เสาร์เปิด 14:15–23:00' },
  { id: 't7', k: 'view', name: 'แท่น Memorial · โค้ง 7–8', x: 37.4, y: 27.2, info: 'Zone 4' },
  { id: 't1112', k: 'view', name: 'แท่นโค้ง 11–12', x: 9.9, y: 43.7, info: 'Zone 4' },
  { id: 't1314', k: 'view', name: 'แท่น Esplanade Drive · โค้ง 13–14', x: 18.4, y: 55.8, info: 'Zone 4' },
  { id: 't1415', k: 'view', name: 'แท่น Raffles Ave · โค้ง 14–15', x: 35.7, y: 43.2, info: 'Zone 4' },
  { id: 't13', k: 'view', name: 'แท่นโค้ง 1–3 / Pit Exit', x: 82.8, y: 46.5, info: 'Zone 1' },
  { id: 't5', k: 'view', name: 'แท่นโค้ง 5', x: 73.6, y: 61.7, info: 'Zone 1' },
];

const GATES_TEXT = [
  ['Gate 1 (Republic Blvd) · Zone 1', 'Nicoll Highway ทางออก B (Circle Line) เดิน 7 นาที — ใกล้ Wharf Stage และโค้ง 1–3'],
  ['Gate 2 (Temasek Ave) · Zone 2', 'Promenade ทางออก C (Circle / Downtown Line) — ใกล้ Flyer และโค้ง 5'],
  ['Gate 3A / 3B (Stamford) · Zone 4', 'City Hall ทางออก A เดิน 5–10 นาที หรือ Esplanade ทางออก F — ใกล้ Memorial และ Padang'],
  ['Gate 4 (Empress) · Zone 4', 'Raffles Place ทางออก A หรือ B เดิน 10 นาที — ติดโค้ง 11–12 และ Waterside'],
  ['Gate 5 (Fullerton) / Gate 6 (Jubilee) · Zone 4', 'Raffles Place เดิน 10 นาที'],
  ['Gate 7 (Marina Square) · Zone 4', 'City Hall ทางออก A หรือ Esplanade ทางออก C — ริม Raffles Avenue'],
  ['Gate 8 (Helix) · Zone 2', 'Bayfront ทางออก E เดิน 10 นาที (ขาออกใช้ทางออก B)'],
];

const PACK = [
  ['shoes', 'รองเท้าที่เดินและยืนนานได้', 'ทางการบอกว่าอาการที่เจอบ่อยสุดในสนามคือเท้าพอง ขาดน้ำ และผิวไหม้แดด'],
  ['ear', 'ที่อุดหู', 'มีขายที่บูธสินค้าในสนามด้วย'],
  ['power', 'Power bank + สายชาร์จ', 'บัตรเข้าสนามอยู่ในแอป แบตหมด = เข้าไม่ได้ · ในสนามมีจุดเช่า power bank ใกล้ Information Booth'],
  ['rain', 'เสื้อกันฝน (poncho)', 'งานจัดทุกสภาพอากาศ · บนแท่นดูรถไม่ควรกางร่มเพราะบังคนอื่น'],
  ['water', 'ขวดน้ำเปล่าไม่เกิน 1 ลิตร 1 ขวด', 'ห้ามขวดแก้วและกระป๋อง เติมน้ำฟรีที่ Water Point ในสนาม'],
  ['bag', 'กระเป๋าไม่เกิน 20 ลิตร', 'ใบเล็กผ่านจุดตรวจเร็วกว่า'],
  ['app', 'แอป Singapore GP + บัตรโหลดไว้แล้ว', 'ภาพหน้าจอ วิดีโอ หรือกระดาษพิมพ์ใช้เข้าประตูไม่ได้'],
  ['sun', 'ครีมกันแดด + หมวก', 'ประตูเปิดตั้งแต่บ่าย แดดยังแรง'],
  ['cash', 'เงินสดดอลลาร์สิงคโปร์', 'ศูนย์อาหารหลายร้านรับเงินสดเป็นหลัก'],
  ['card', 'บัตรที่ใช้แตะ MRT/รถเมล์', 'บัตรธนาคารต่างประเทศแบบ contactless มีค่าธรรมเนียม S$0.60 ต่อวันที่ใช้'],
  ['temple', 'เสื้อคลุม/ผ้าคลุมไหล่สำหรับเข้าวัด', 'วัดพระเขี้ยวแก้วงดเสื้อเปิดไหล่และกางเกง-กระโปรงสั้น'],
  ['doc', 'พาสปอร์ต + SG Arrival Card', 'กรอกออนไลน์ล่วงหน้าก่อนถึง'],
];

const TIPS = [
  ['🎟️ ก่อนถึงจุดตรวจ', 'เปิดแอปเตรียมบัตรไว้ เปิดกระเป๋ารอ ถือขวดน้ำไว้ในมือ', 'ok', [SRC.ticketing, SRC.prohibited]],
  ['🚫 ห้ามนำเข้า (กฎปี 2026)', 'กระเป๋าเกิน 20 ลิตร · อาหารและเครื่องดื่มจากข้างนอก · ขวดแก้ว/กระป๋อง · น้ำเกิน 1 ลิตรต่อขวดต่อคน · กล้องมืออาชีพ/เลนส์ที่ยาวรวมเกิน 30 ซม. · ไม้เซลฟี่ที่ยืดเกิน 30 ซม. · เก้าอี้/ม้านั่ง · โดรน · เลเซอร์ — รายการไม่ครบทุกข้อ เจ้าหน้าที่ตัดสินหน้างาน', 'ok', [SRC.prohibited]],
  ['🔋 Power bank / ที่อุดหู', 'หน้ากฎของทางการไม่ได้ระบุว่าห้าม power bank หรือที่อุดหู และในสนามมีบริการเช่า power bank กับขายที่อุดหู จึงน่าจะนำเข้าได้ แต่ไม่มีข้อความยืนยันตรง ๆ', 'unk', [SRC.prohibited, SRC.gear]],
  ['🧍 เข้าคิวแท่นดูรถ', 'ไม่มีที่นั่งจองและไม่รับประกันตำแหน่ง ไปก่อนเวลา 30–45 นาทีสำหรับเซสชันใหญ่ ก่อนเริ่มนั่งพักบนขั้นได้ พอรถวิ่งเจ้าหน้าที่อาจให้ยืน (ประสบการณ์ปี 2025)', 'prev', [SRC.note]],
  ['💧 น้ำและเวลาพัก', 'เติมน้ำทุกครั้งที่ผ่าน Water Point ช่วงว่างที่ควรพักจริง: เสาร์ 15:40–16:30 และ 17:40–18:45 · อาทิตย์ 16:15–18:00', 'tip', [SRC.gear, SRC.map]],
  ['🙏 เข้าวัด', 'แต่งกายสุภาพ ปิดไหล่และเข่า พูดเบา ไม่ถ่ายรูปในจุดที่มีป้ายห้าม', 'tip', [SRC.btrt]],
  ['🎤 โซนหน้าเวที Padang', 'เข้าตามลำดับมาก่อนได้ก่อน ออกได้ตลอด แต่ถ้าเต็มแล้วอาจกลับเข้าไม่ได้', 'ok', [SRC.fanzone]],
  ['📶 Wi-Fi ในสนาม', 'มีที่ประตูผู้ชมทุกประตูและ Information Booth', 'ok', [{ label: 'singaporegp.sg – Wi-Fi Connectivity', url: 'https://singaporegp.sg/en/event-info/eventguide/event-tips/wifi-connectivity/' }]],
  ['🚕 แท็กซี่หลังงาน', 'มีค่าเพิ่ม S$8 สำหรับเที่ยวที่ขึ้นจากจุดที่กำหนด ช่วง 21:30–00:00 วันที่ 9–11 ต.ค.', 'ok', [SRC.lta]],
];

/* พิกัดสำหรับเทียบกับตำแหน่งของฉัน — a:true = พิกัดโดยประมาณ */
const LOCS = {
  hotel: { n: 'Hotel 81 Dickson', p: [1.3049377, 103.854273] },
  changi: { n: 'Changi Airport T2', p: [1.3554, 103.9886], a: true },
  padang: { n: 'Padang Stage', p: [1.29087, 103.85263] },
  waterside: { n: 'Waterside Stage', p: [1.28886, 103.85326] },
  wharf: { n: 'Wharf Stage', p: [1.29738, 103.86333] },
  flyer: { n: 'Singapore Flyer', p: [1.2893, 103.8631], a: true },
  memorial: { n: 'Memorial · โค้ง 7–8', p: [1.2929, 103.8547], a: true },
  t13: { n: 'โค้ง 1–3', p: [1.2948, 103.8628], a: true },
  t1314: { n: 'Esplanade Drive · โค้ง 13–14', p: [1.2880, 103.8545], a: true },
  t1112: { n: 'โค้ง 11–12 / Anderson Bridge', p: [1.2873, 103.8531], a: true },
  maxwell: { n: 'Maxwell Food Centre (Ah Tai)', p: [1.28043, 103.8447], a: true },
  btrt: { n: 'Buddha Tooth Relic Temple', p: [1.2815155, 103.8442397] },
  kwanim: { n: 'Kwan Im Thong Hood Cho Temple', p: [1.3008576, 103.8529932] },
  ngkuan: { n: 'Ng Kuan Chilli Pan Mee', p: [1.300899, 103.8518022] },
  tbb: { n: 'Tiong Bahru Bakery Foothills', p: [1.2913, 103.8452], a: true },
  acm: { n: 'Asian Civilisations Museum / Gate 4', p: [1.2875002, 103.8513853] },
  s_cityhall: { n: 'City Hall MRT', p: [1.2931, 103.8520], a: true },
  s_esplanade: { n: 'Esplanade MRT', p: [1.2934, 103.8554], a: true },
  s_promenade: { n: 'Promenade MRT', p: [1.2932, 103.8610], a: true },
  s_nicoll: { n: 'Nicoll Highway MRT', p: [1.2998, 103.8636], a: true },
  s_bugis: { n: 'Bugis MRT', p: [1.3009, 103.8559], a: true },
  s_jalanbesar: { n: 'Jalan Besar MRT', p: [1.3053, 103.8553], a: true },
  s_rochor: { n: 'Rochor MRT', p: [1.3037, 103.8526], a: true },
  s_chinatown: { n: 'Chinatown MRT', p: [1.2847, 103.8440], a: true },
  s_bayfront: { n: 'Bayfront MRT', p: [1.2817, 103.8591], a: true },
  s_raffles: { n: 'Raffles Place MRT', p: [1.2840, 103.8514], a: true },
  s_fortcanning: { n: 'Fort Canning MRT', p: [1.2927804, 103.8444139] },
  s_bencoolen: { n: 'Bencoolen MRT', p: [1.2986, 103.8500], a: true },
  s_expo: { n: 'Expo MRT', p: [1.3354, 103.9614], a: true },
  bkk: { n: 'สนามบินสุวรรณภูมิ', p: [13.69, 100.7501], a: true },
};
/* กิจกรรม → จุดหมาย (ที่ไม่มีในนี้ = ยังไม่ระบุสถานที่) */
const EVLOC = {
  'd1-fly': 'changi', 'd1-imm': 'changi', 'd1-ci': 'hotel', 'd1-cortis': 'padang', 'd1-sq': 'memorial',
  'd2-wake': 'hotel', 'd2-ct': 'maxwell', 'd2-flyer': 'flyer', 'd2-ff': 'wharf', 'd2-sprint': 't13', 'd2-zara': 'padang', 'd2-hyo': 'waterside', 'd2-q': 't1112', 'd2-killers': 'padang',
  'd3-wake': 'hotel', 'd3-temple': 'kwanim', 'd3-free': 'tbb', 'd3-porsche': 't1112', 'd3-lana': 'padang',
  'd4-wake': 'hotel', 'd4-co': 'hotel', 'd4-ci': 'changi', 'd4-fly': 'changi',
};

/* ภาพจากหน้าบัตรของทางการ — ทางการไม่ได้ระบุปีที่ถ่ายและตำแหน่ง คำว่า "น่าจะ" คือเดาจากสิ่งที่เห็นในภาพ */
const OFF = 'https://storage.singaporegp.sg/web/2026/tickets/';
const GALLERY = [
  { z: 1, url: 'https://storage-uat.singaporegp.sg/web/2026/tickets/180-photos/premier-walkabout.jpg', cap: 'มุมกว้างจากพื้นที่ Premier Walkabout: เห็นอาคาร Paddock Club, Singapore Flyer และป้ายเส้นชัย น่าจะเป็นปลายทางตรงหน้าพิทใต้สะพาน Benjamin Sheares · คนยืนเต็มแนวรั้ว' },
  { z: 1, url: OFF + 'premier-walkabout/premier-walkabout-2.jpg', cap: 'ยืนดูใต้โครงสะพาน รถผ่านใกล้หลังรั้วตาข่าย น่าจะเป็นช่วงโค้ง 1–3 · คนยืนซ้อนหลายแถว' },
  { z: 1, url: OFF + 'premier-walkabout/premier-walkabout-1.jpg', cap: 'ภาพมุมสูงของแท่น Walkabout แบบขั้นบันได คนเต็มแท่น มีรั้วสองชั้นระหว่างแท่นกับแทร็ก · ไม่ทราบตำแหน่ง' },
  { z: 1, url: OFF + 'premier-walkabout/premier-walkabout-4.jpg', cap: 'ช่วงกลางวัน คนยืนชิดรั้วยกมือถือถ่ายรถ · ไม่ทราบตำแหน่ง' },
  { z: 1, url: OFF + 'premier-walkabout/premier-walkabout-3.jpg', cap: 'ช่วงกลางคืน มองข้ามหัวคนดูไปที่แทร็ก เห็น Flyer ด้านหลัง · ไม่ทราบตำแหน่ง' },
  { z: 4, url: 'https://storage-uat.singaporegp.sg/web/2026/tickets/180-photos/zone-4-walkabout.jpg', cap: 'มุมกว้างจากแท่น Zone 4 Walkabout ตอนกลางคืน: แท่นยกสูง มองลงเห็นทางตรงและรั้วตาข่าย · ไม่ทราบตำแหน่ง' },
  { z: 4, url: OFF + 'zone-4-walkabout/zone-4-walkabout-4.jpg', cap: 'แท่น Zone 4 เห็นหลังคา Esplanade ด้านหลัง น่าจะเป็นริม Esplanade Drive · คนเต็มแท่น' },
  { z: 4, url: OFF + 'zone-4-walkabout/zone-4-walkabout-1.jpg', cap: 'ยืนระดับพื้นชิดรั้ว รถผ่านใกล้มาก · ไม่ทราบตำแหน่ง' },
  { z: 4, url: OFF + 'zone-4-walkabout/zone-4-walkabout-2.jpg', cap: 'ยืนดูใต้ต้นไม้ มีรั้วและกำแพงคอนกรีตคั่น ฝั่งตรงข้ามเป็นอัฒจันทร์ · ไม่ทราบตำแหน่ง' },
];
